name: Auto-label Issues

on:
  issues:
    types: [opened] # Trigger the workflow when a new issue is opened

jobs:
  label-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Label issue
      uses: actions/labeler@v2 # Using a community-maintained GitHub Action for labeling issues
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }} # Token to access the repository
        labels: |
          bug: issue-name-contains.contains('bug')
          enhancement: issue-body-includes.contains('feature request') || issue-body-includes.contains('enhancement')
